version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 30000:30000
      - 50000:50000
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  net:
